config/routes.rb
Rails.application.routes.draw do


  get 'requests/index'
  get 'requests/new'
  get 'requests/edit'
  get 'requests/show'
  get 'products/index'
  get 'products/new'
  get 'products/edit'
  get 'products/show'
  get 'branches/index'
  get 'branches/new'
  get 'branches/edit'
  get 'branches/show'
  get 'users/index'
  get 'users/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root :to => 'session#create'

resources :users  #, :only => [:new,:create,:index]
#
get '/login' => 'session#new'
post '/login' => 'session#create'
# delete '/login' => 'session#destroy'

resources :branches
resources :products
resources :requests
resources :users

post '/requests/create' => 'requests#create'
post '/products/create' => 'products#create'
post '/branches/create' => 'branches#create'
post '/requests/:id/update' => 'requests#update'
post '/branches/:id/update' => 'branches#update'
post '/products/:id/update' => 'products#update'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch.rb
class Branch < ActiveRecord::Base
  belongs_to :user, :optional => true
  scope :filter_by_user, -> (user_id) { where user_id: @current_user.id }
  has_many :requests
end

app/models/product.rb
class Product < ActiveRecord::Base
has_many :requests
end

app/models/request.rb
class Request < ActiveRecord::Base
belongs_to :branch, :optional => true
belongs_to :product, :optional => true
end

app/models/user.rb
class User < ActiveRecord::Base
has_secure_password
validates :email, :presence => true, :uniqueness => true
has_many :branches  #Relationship between Models

# scope :filter_by_email, -> (email) { where email: email }
# scope :filter_by_password, -> (password) { where password: password }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token #This is required for APIs
  before_action :fetch_user

     private
     def fetch_user
       # @current_user = User.find_by :name => params[:name]
       @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
       session[:user_id] = nil unless @current_user.present?
     end

     def check_for_login
       redirect_to login_path unless @current_user.present?
     end

     def check_for_admin
       redirect_to root_path unless @current_user.present? && @current_user.admin?
     end
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController

  def index
    @branches = Branch.all
    # @branches = Branch.find_by :user_id => @current_user
    render json: @branches
  end

  def new
    @branch = Branch.new
  end

  def create
    branch = Branch.create branch_params
    render json: branch
  end

    #Edit branch
  def edit
    @branch = Branch.find params[:id]
  end

    #Update branch
  def update
    @branch = Branch.find params[:id]
    @branch.update branch_params
    render json: @branch
  end

    #Show branch
  def show
    @branch = Branch.find params[:id]
  end

    #Delete branch
  def destroy
    branch = Branch.find params[:id]
    branch.destroy
    render json: Branch
  end

  private
    #Private methods
  def branch_params
    params.require(:branch).permit(:branch_name,:location, :email, :contact, :user_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    render json: @products
  end

  def new
    @product = Product.new
  end

  #Create product
  def create
    product = Product.create product_params
    render json: product
  end

#Edit product
  def edit
    @product = Product.find params[:id]
  end

#Update product
  def update
    product = Product.find params[:id]
    product.update product_params
    render json: product
  end

#Show product
  def show
    @product = Product.find params[:id]
  end

#Delete product
  def destroy
    product = Product.find params[:id]
    product.destroy
    render json: Product
  end

#Private Methods
  private
   def product_params
     params.require(:product).permit(:item, :price, :image)
   end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def index
    @requests = Request.all
    # @requests = Request.find_by :branch_id => params[:branch_name]
    render json: @requests
  end

  def new
    @request = Request.new
  end

  def create
    request = Request.create request_params
    render json: request
  end

  #Edit request
  def edit
    @request = Request.find params[:id]
  end

#Update request
  def update
    request = Request.find params[:id]
    request.update request_params
    render json: request
  end

#Show request
  def show
    @request = Request.find params[:id]
  end

#Delete request
  def destroy
    request = Request.find params[:id]
    request.destroy
    render json: Request
  end

#Private Methods
  private
   def request_params
     params.require(:request).permit(:status, :created_at, :branch_id, :product_id, :price, :quantity)
   end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  #New Session
    def new
      end

  #Create Session
    def create
      user = User.find_by :email => params[:email]
      if user.present? && user.authenticate(params[:password])
        session[:user_id] = user.id # Log the user in
        # redirect_to root_path
      else
        flash[:error] = "Invalid email address or password"
        # redirect_to login_path
      end
    end

  #Destroy Session
    def destroy
      session[:user_id] = nil # Log the user out
      redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :check_for_admin, :only => [:index]  #call before action


#Index
  def index
    @users = User.all

    # @user = User.find_by :name => params[:name]

    # if user.present? && user.authenticate(params[:password])
    #   render json: user
    #   # session[:user_id] = user.id # Log the user in
    #   # redirect_to root_path
    # else
    #   flash[:error] = "Invalid email address or password"
    #   # redirect_to login_path
    # end

    # @users = User.where(nil)
    # filtering_params(params).each do |key, value|
    #     @users = @users.public_send("filter_by_#{key}") if value.present?
    #      render json: @users
    #   end


  end

#New User
  def new
    # @user = User.new
  end

#Create User
  def create
    # @user = User.new user_params
    # if @user.save
    #   session[:user_id] = @user.id
    #   redirect_to
    # else
    #   render :new
    # end
  end


#Private Methods
  private
  # def user_params
  #   params.require(:user).permit(:name, :email, :password, :password_confirmation)
  # end

  # def filtering_params(params)
  #     params.slice(:id, :email, :password, :admin)
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/branches/_form.html.erb
<div class="form-group">
<%= form_for @branch do |f| %>
  <%= f.label :branch_name, :class=>"form-control col-md-2" %>
  <%= f.text_field :branch_name, :required => true, :autofocus => true, :class=>"form-control col-md-4" %>
  <br>
  <%= f.label :location, :class=>"form-control col-md-2" %>
  <%= f.text_field :location, :class=>"form-control col-md-4" %>
  <br>
  <%= f.label :email, :class=>"form-control col-md-2" %>
  <%= f.text_field :email, :class=>"form-control col-md-4" %>
  <br>
  <%= f.label :contact, :class=>"form-control col-md-2" %>
  <%= f.text_field :contact, :class=>"form-control col-md-4" %>
  <br>
  <%= f.label :user_id, :class=>"form-control col-md-2" %>
  <%= f.text_field :user_id, :class=>"form-control col-md-4" %>
  <br>
  <%= f.submit class: "btn btn-primary btn-lg"  %>

<% end %>
</div>

app/views/branches/edit.html.erb
<h1>Editing Branch</h1>

<%= render 'form', branch: @branch %>

<%= link_to 'Show', @branch %> |
<%= link_to 'Back', branches_path %>

app/views/branches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Branches</h1>

<table>
  <thead>
    <tr>
      <th>Branch name</th>
      <th>Location</th>
      <th>Email</th>
      <th>Contact</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @branches.each do |branch| %>
      <tr>
        <td><%= branch.branch_name %></td>
        <td><%= branch.location %></td>
        <td><%= branch.email %></td>
        <td><%= branch.contact %></td>
        <td><%= branch.user_id %></td>
        <td><%= link_to 'Show', branch %></td>
        <td><%= link_to 'Edit', edit_branch_path(branch) %></td>
        <td><%= link_to 'Destroy', branch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Branch', new_branch_path %>

app/views/branches/new.html.erb
<h1>New Branch</h1>

<%= render 'form', branch: @branch %>

<%= link_to 'Back', branches_path %>

app/views/branches/show.html.erb
<h1>branches#show</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarketFlow</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/login/new.html.erb
<h2>Log in</h2>

app/views/products/_form.html.erb
<%= form_for @product do |form| %>

    <%= form.label :item %>
    <%= form.text_field :item %>

    <%= form.label :price %>
    <%= form.text_field :price %>

    <%= form.label :image %>
    <%= form.text_field :image %>

  <%= form.submit %>
<% end %>

app/views/products/edit.html.erb
<h1>Products#edit</h1>


<%= render 'form', products: @products %>

<%= link_to 'Show', @products %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Price</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.item %></td>
        <td><%= product.price %></td>
        <td><%= product.image %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>

app/views/requests/_form.html.erb
<%= form_for @request do |form| %>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :branch_id %>
    <%= form.number_field :branch_id %>
  </div>
    <div class="field">
    <%= form.label :product_id %>
    <%= form.number_field :product_id %>
  </div>

    <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>


    <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :created_at %>
    <%= form.date_select :created_at %>
  </div>

<%= form.submit   %>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Requests</h1>

<%= render 'form', request: @request %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Requests</h1><br>

<table>
  <thead>
    <tr>
      <th>Status</th><br>
      <th>Branch</th><br>
      <th>Product</th><br>
      <th>Quantity</th>
      <th>Price</th>
      <th>Created at</th><br>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.status %></td>
        <td><%= request.branch_name %></td>
        <td><%= request.product_id %></td>
          <td><%= request.quantity_id %></td>
        <td><%= request.price %></td>
        <td><%= request.created_at %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form', request: @request %>

app/views/requests/show.html.erb
<h1>Requests#show</h1>

app/views/session/new.html.erb
<h1>Session#new</h1>

<%= form_tag login_path do %>
    <fieldset>
        <%= label_tag :email %>
        <%= email_field_tag :email %>
    </fieldset>

    <fieldset>
        <%= label_tag :password %>
        <%= password_field_tag :password %>
    </fieldset>

    <%= submit_tag "Log in"  %>
<% end %>

<% if flash[:error].present? %>
    <h2><%= flash[:error] %></h2>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>

<% @users.each do |user| %>
<%= user.name%> <br/>
<%= user.email%> <br/>
<%= user.password_digest%> <br/>
<%= user.admin%> <br/>

<% end %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>